CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  email VARCHAR(254) NOT NULL,
  name VARCHAR(250) NOT NULL,
  registration_date TIMESTAMP NOT NULL,
  CONSTRAINT pk_user PRIMARY KEY (id),
  CONSTRAINT UQ_USER_EMAIL UNIQUE (email),
  UNIQUE(id)
);

CREATE TABLE IF NOT EXISTS categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name VARCHAR(50) NOT NULL,
  registration_date TIMESTAMP NOT NULL,
  CONSTRAINT pk_category PRIMARY KEY (id),
  CONSTRAINT UQ_CATEGORY_NAME UNIQUE (name),
  UNIQUE(id)
);

CREATE TABLE IF NOT EXISTS locations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  lat FLOAT NOT NULL,
  lon FLOAT NOT NULL,
  CONSTRAINT pk_location PRIMARY KEY (id),
  UNIQUE(id)
);

CREATE TABLE IF NOT EXISTS events (
  annotation VARCHAR(2000) NOT NULL,
  category_id BIGINT NOT NULL,
  confirmed_requests INTEGER,
  created_on TIMESTAMP,
  description VARCHAR(7000),
  event_date TIMESTAMP NOT NULL,
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  initiator_id BIGINT NOT NULL,
  location_id BIGINT NOT NULL,
  paid BOOLEAN NOT NULL,
  participant_limit INTEGER,
  published_on TIMESTAMP,
  request_moderation BOOLEAN,
  state VARCHAR(20),
  title VARCHAR(120) NOT NULL,
  views BIGINT,
  CONSTRAINT pk_event PRIMARY KEY (id),
  CONSTRAINT fk_events_to_categories FOREIGN KEY(category_id) REFERENCES categories(id),
  CONSTRAINT fk_events_to_users FOREIGN KEY(initiator_id) REFERENCES users(id),
  CONSTRAINT fk_events_to_locations FOREIGN KEY(location_id) REFERENCES locations(id),
  UNIQUE(id)
);

CREATE TABLE IF NOT EXISTS requests (
  created TIMESTAMP NOT NULL,
  event_id BIGINT NOT NULL,
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  requester_id BIGINT NOT NULL,
  status VARCHAR(20),
  CONSTRAINT pk_request PRIMARY KEY (id),
  CONSTRAINT fk_requests_to_events FOREIGN KEY(event_id) REFERENCES events(id),
  CONSTRAINT fk_requests_to_users FOREIGN KEY(requester_id) REFERENCES users(id),
  UNIQUE(id)
);

CREATE TABLE IF NOT EXISTS compilations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  pinned BOOLEAN NOT NULL,
  title VARCHAR(50),
  created TIMESTAMP NOT NULL,
  CONSTRAINT pk_compilation PRIMARY KEY (id),
  UNIQUE(id),
  UNIQUE(title)
);

CREATE TABLE IF NOT EXISTS events_compilations (
  event_id BIGINT NOT NULL,
  compilation_id BIGINT NOT NULL,
  CONSTRAINT fk_events_compilations_to_events FOREIGN KEY(event_id) REFERENCES events(id),
  CONSTRAINT fk_events_compilations_to_compilations FOREIGN KEY(compilation_id) REFERENCES compilations(id)
);